### ISSUE TITLE
Individual User Page

### ISSUE THREAD

**Issue by stein-key** [Firm-Collective/One-Accord#12]
When a user wants to make changes to their account or view their activity I want them to be able to go to their Usage Page to be a central location for them to make changes.

AC:
Activity 
- Timer event participation: how many time each icon was clicked
- Shared posts history 

User settings
- Email
> - checks if email is unique if changed 
- Username
> - checks if username is unique if changed 
- Location selection 
- Profile pic 

Sub Tickets:

- [ ] https://github.com/Firm-Collective/One-Accord/issues/34
- [ ]  https://github.com/Firm-Collective/One-Accord/issues/35
- [ ]  https://github.com/Firm-Collective/One-Accord/issues/36
- [ ]  https://github.com/Firm-Collective/One-Accord/issues/37
- [ ]  https://github.com/Firm-Collective/One-Accord/issues/38

**Comment by jevens007** [comment]
- Consider having interesting facts about the user self identified which creates standardized data tags. For example, they can optionally share their language preference and proficiency, even if the app is currently only in English. Example: I am a Chilean BSSM student, I will read the app in English; however, when I am moved to post, I may do this in my native Spanish. I would like to submit to the system that I am native Spanish and Advanced English speaker in my 'bio'
- This would help for future analytics as well as filtering content in multiple languages. In future, those who share the same language blocks could be recommended as possible connections or targeted marketing for their language groups.

**Comment by Negotiator05** [comment]
The pink team would like this ticket.

**Comment by timbo84** [comment]
I have noticed that one thing that wants to be done is changing a profile picture. In the schema of profile, profile picture is not one of the objects. are we allowed to change the schema? or should we get a hold of someone higher up first?

**Comment by Jmoody22** [comment]
Yes, they are located in the Figma file under the profile section.
