### ISSUE TITLE
example ticket

### ISSUE THREAD

**Issue by stein-key** [Firm-Collective/One-Accord#30]
dfhfghfhfd

Ac:

sub taickets:
- [ ] think is my sub task
- [x] https://github.com/Firm-Collective/One-Accord/issues/31
- [ ] https://github.com/Firm-Collective/One-Accord/issues/33
