### ISSUE TITLE
Launch Day Countdown Timer

### ISSUE THREAD

**Issue by stein-key** [Firm-Collective/One-Accord#6]
**High-level Summary:**
This timer helps facilitate the synchronized actions of praying and worshiping throughout the Launch Day Event. Because the timer will be repeating a countdown throughout the day until the next type of action, users can hop in and participate as they are able to.  

**User Story:**
- As a public viewer, I can see the timer and the actions prompts so that I'm encouraged to participate.
- When a public viewer sees the timer and action set for that countdown period, I want them to be prompted to sign up so that they can participate 
- As a user, I can see the timer and I'm prompted to click/acknowledge/participate in the action for that countdown period
- As a user, my participation is highlighted on the map view 
- When a user clicks the action button, capture the total amount of users who have clicked and display so that we can see the total amount of users who have clicked during that countdown cycle

**AC:**
- Over the course of a full day from each end of the globe, run a countdown timer where every X min it counts down to the next action/prayer to participate in
- Every X minutes a single button action will be highlighted to click 
- capture click count and display 

Sub Tickets:

- [ ] https://github.com/Firm-Collective/One-Accord/issues/39
- [ ] https://github.com/Firm-Collective/One-Accord/issues/60
- [ ] https://github.com/Firm-Collective/One-Accord/issues/67

**Comment by drewdevvv** [comment]
@jevens007 If I'm not mistaken, my understanding is that the launch day time is a static state that other timezones would relate to dynamically. So if launch is 4/12/24 at 8PM PDT -> 4/13/24 5AM CEST

**Comment by SustainableCoder** [comment]
Hello,

I'm just piggybacking on the previous question on when the webapp would go live or the timer would start... (I'm not sure if they are one in the same...) I understood that question about "So if launch is 4/12/24 at 8PM PDT -> 4/13/24 5AM CEST" to mean should we start the event when it's Pentecost somewhere in the world, or will we start the event from a certain timezone in the US, for example, but Pentecost day has already started in another part of the world.
